### ISSUE TITLE
我Fork了你的GhostBot 把RSS 换成了 Ghost 开放API

### ISSUE THREAD

**Issue by LunaYJ** [wssgcg1213/GhostBot#1]
RSS只显示最近的15篇文章，所以当文章数大于15的话，而要寻找最近15篇以前的文章的话，就无法通过rss搜索到，于是就想到了使用Ghost public api 来作为搜索源。。。
把一开始 loadRss的步骤 改换成 loadAPI

**Comment by wssgcg1213** [comment]
这个项目很久没有维护了~  have fun :)

**Comment by wssgcg1213** [comment]
方便的话可以提一个pr

**Comment by LunaYJ** [comment]
已发PR
